import { test, expect } from "@playwright/test";
test.use({ trace: "off" });
test("native browser dialogs, popups, tracing, console and failed request capture work", async ({ browser }, info) => {
  const context = await browser.newContext({ baseURL: "http://127.0.0.1:3020" });
  const page = await context.newPage();
  await context.tracing.start({ screenshots: true, snapshots: true });
  const consoleErrors: string[] = [];
  const failedRequests: string[] = [];
  page.on("console", message => { if (message.type() === "error") consoleErrors.push(message.text()); });
  page.on("requestfailed", request => failedRequests.push(request.url()));
  await page.goto("/updates");
  page.once("dialog", async dialog => { expect(dialog.message()).toBe("Local QA dialog"); await dialog.dismiss(); });
  await page.evaluate(() => window.confirm("Local QA dialog"));
  const popupPromise = page.waitForEvent("popup");
  await page.evaluate(() => window.open("/about-nashmi", "_blank"));
  const popup = await popupPromise;
  await popup.waitForLoadState();
  await expect(popup.locator("main")).toBeVisible();
  await popup.close();
  await page.route("**/qa-synthetic-failure", route => route.abort("failed"));
  await page.evaluate(async () => { await fetch("/qa-synthetic-failure").catch(() => {}); console.error("Synthetic QA console error"); });
  expect(consoleErrors).toContain("Synthetic QA console error");
  expect(failedRequests.some(url => url.endsWith("/qa-synthetic-failure"))).toBe(true);
  const screenshot = info.outputPath("browser-capabilities.png");
  await page.screenshot({ path: screenshot });
  await info.attach("browser-capabilities", { path: screenshot, contentType: "image/png" });
  const trace = info.outputPath("capabilities-trace.zip");
  await context.tracing.stop({ path: trace });
  await info.attach("capabilities-trace", { path: trace, contentType: "application/zip" });
  await context.close();
});
